force-app/main/default/objects/External_Account__x.object
<CustomObject>
    <externalDataSource>ExternalAccountDataSource</externalDataSource>
    <externalName>Account</externalName>
    <label>External Account</label>
    <pluralLabel>External Accounts</pluralLabel>
    <fields>
        <fullName>Erp_Id__c</fullName>
        <externalId>true</externalId>
        <label>Erp Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ConnectService.cls
public with sharing class ConnectService {

    public static List<External_Account__x> queryExternalAccounts() {
        return [
            SELECT Id, Name__c, Status__c, Erp_Id__c
            FROM External_Account__x
            ORDER BY Erp_Id__c
            LIMIT 200
        ];
    }

    public static List<AggregateResult> mixedJoin() {
        return [
            SELECT Account.Name localName, External_Account__r.Name__c externalName
            FROM External_Account__x
            LIMIT 200
        ];
    }

    public static Integer sourceCount() {
        return [SELECT COUNT() FROM External_Account__x];
    }
}