force-app/main/default/objects/Headless_Architecture__c.object
<CustomObject>
    <label>Headless Architecture</label>
    <pluralLabel>Headless Architectures</pluralLabel>
    <nameField>
        <label>Headless Architecture Name</label>
        <type>Text</type>
    </nameField>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>1024</length>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Layer__c</fullName>
        <label>Layer</label>
        <picklist>
            <picklistValues>
                <fullName>Data 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Logic 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orchestration 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement 360</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <searchSettings>
        <searchResultAdditionalFields>NAME</searchResultAdditionalFields>
        <searchResultsByObject>
            <searchResultFields>NAME</searchResultFields>
        </searchResultsByObject>
    </searchSettings>
</CustomObject>

force-app/main/default/classes/HeadlessFundamentalsService.cls
@SuppressWarnings('PMD.AvoidDebugStatements')
public with sharing class HeadlessFundamentalsService {

    public static final Integer MAX_QUERY_ROWS = 2000;

    public enum Layer { DATA_360, BUSINESS_LOGIC_360, ORCHESTRATION_360, ENGAGEMENT_360 }

    public static void logHeadlessFact(String title, String detail, Layer layer) {
        Headless_Architecture__c fact = new Headless_Architecture__c(
            Name = 'HF-' + System.currentTimeMillis(),
            Title__c = title,
            Detail__c = detail,
            Layer__c = layer.name()
        );
        insert fact;
    }

    public static List<Headless_Architecture__c> getFactsByLayer(Layer layer) {
        return [
            SELECT Id, Name, Title__c, Detail__c
            FROM Headless_Architecture__c
            WHERE Layer__c = :layer.name()
            ORDER BY CreatedDate
        ];
    }

    public static String apiForNeed(String need) {
        Map<String, String> map = new Map<String, String>{
            'CRUD' => 'REST API / GraphQL',
            'NESTED' => 'GraphQL',
            'BACKFILL' => 'Bulk API 2.0',
            'STREAM' => 'Streaming API / Platform Events',
            'APEX' => 'Apex REST',
            'WORKER' => 'Functions / Express worker'
        };
        return map.get(need?.toUpperCase());
    }
}